# Fichier définissant les contraintes
# pour l'analyse des fichiers du projet

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: true
#    - always_declare_return_types
#    - always_specify_types
#    - avoid_double_and_int_checks
#    - avoid_empty_else
#    - avoid_init_to_null
#    - avoid_renaming_method_parameters
#    - avoid_returning_null_for_void
#    - avoid_unnecessary_containers
#    #    - avoid_unused_constructor_parameters
#    - await_only_futures
#    - empty_catches
#    - empty_constructor_bodies
#    - empty_statements
#    - literal_only_boolean_expressions
#    - missing_whitespace_between_adjacent_strings
#    - unawaited_futures
#    #    - unnecessary_await_in_return
#    #    - unnecessary_const
#    #    - unnecessary_lambdas
#    - unnecessary_new
#    #    - unnecessary_null_aware_assignments
#    #    - unnecessary_null_checks
#    #    - unnecessary_null_in_if_null_operators
#    #    - unnecessary_nullable_for_final_variable_declarations
#    #    - unnecessary_overrides
#    #    - unnecessary_parenthesis
#    #    - unnecessary_statements
#    #    - unnecessary_this
#    - unrelated_type_equality_checks
#    #    - unsafe_html
#    #    - use_function_type_syntax_for_parameters
#    #    - use_named_constants
#    #    - use_raw_strings
#    - use_rethrow_when_possible
#    - prefer_const_declarations
#    - prefer_const_constructors

analyzer:
  exclude: [ test/mocks/** ]
  plugins:
    - dart_code_metrics
  errors:
    # ajouter des règles qui imposent de corriger
    empty_statements: error

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    #    cyclomatic-complexity: 20
    #    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    #    - prefer-conditional-expressions
    - no-equal-then-else