name: main-workflow
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: main-workflow

jobs:
  test-analyze:
    uses: ./.github/workflows/01-test-analyze.yml