name: main-workflow
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  test-analyze:
    uses: ./.github/workflows/01-test-analyze.yml